# Use the official Rust image from Docker Hub
FROM rust:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the source code into the container
COPY . .

# Install dependencies
# RUN cargo build --release

